--- #YAML:1.0
name:               Net-DNSBLLookup
version:            0.05
abstract:           Lookup IP Address in Open Proxy and SPAM DNS Blocklists
author:
    - TJ Mather <tjmather@maxmind.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::DNS:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
